// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://moljurgujqtckraxfwby.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vbGp1cmd1anF0Y2tyYXhmd2J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxMjU1ODUsImV4cCI6MjA0ODcwMTU4NX0.0qQtzqp0fCFfJNPBbhpEbUNRVYtWQ11JeGg_-xrEJSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);